creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - age1rzs3z3sc742qcmd97lkq524fwundjvqqajfvpfj5rgvyans7m4jqv57cx7 # admin
          - age1fe2ggep46rlf8eke4sustgzz47ufjmxeslkdcrta2ha7v9rqhumq9v952s # stockholm
