keys:
  - &admin age1rzs3z3sc742qcmd97lkq524fwundjvqqajfvpfj5rgvyans7m4jqv57cx7
  - &stockholm age1lsra6esvxcmt5xq7kgsx2zmsfdlvwdaysegzjd9sh0chzhum44fsnh8m9g
  - &asgard age1dw6my3agpxwmkuy48qhvtq9qykcj3pldxjhh34j2j2wztamaw5yqrlzasm

creation_rules:
  # Desktop-only secrets
  - path_regex: (^|/)home\.yaml$
    key_groups:
      - age:
          - *admin

  # Server-only secrets — each host reads only its own file
  - path_regex: (^|/)stockholm\.yaml$
    key_groups:
      - age:
          - *admin
          - *stockholm

  - path_regex: (^|/)asgard\.yaml$
    key_groups:
      - age:
          - *admin
          - *asgard

  # Shared secrets readable by every host
  - path_regex: (^|/)secrets\.yaml$
    key_groups:
      - age:
          - *admin
          - *stockholm
          - *asgard
