keys:
  - &admin age1rzs3z3sc742qcmd97lkq524fwundjvqqajfvpfj5rgvyans7m4jqv57cx7
  - &finland age1n65hk8zdkhveka05lgpd60emdvf3dmvq9zjc97r3jfnnkd4ntsnsp775zz

creation_rules:
  # Desktop-only secrets
  - path_regex: (^|/)home\.yaml$
    key_groups:
      - age:
          - *admin

  # Server-only secrets — each host reads only its own file
  - path_regex: (^|/)finland\.yaml$
    key_groups:
      - age:
          - *admin
          - *finland

  # Shared secrets readable by every host
  - path_regex: (^|/)secrets\.yaml$
    key_groups:
      - age:
          - *admin
          - *finland
