keys:
  - &admin age1rzs3z3sc742qcmd97lkq524fwundjvqqajfvpfj5rgvyans7m4jqv57cx7
  - &stockholm age1fe2ggep46rlf8eke4sustgzz47ufjmxeslkdcrta2ha7v9rqhumq9v952s

creation_rules:
  # Desktop-only secrets
  - path_regex: (^|/)home\.yaml$
    key_groups:
      - age:
          - *admin

  # Server-only secrets
  - path_regex: (^|/)stockholm\.yaml$
    key_groups:
      - age:
          - *admin
          - *stockholm

  # Shared secrets readable by every host
  - path_regex: (^|/)secrets\.yaml$
    key_groups:
      - age:
          - *admin
          - *stockholm
